// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexer.jflex


 /*  Esta seção é copiada antes da declaração da classe do analisador léxico.
  *  É nesta seção que se deve incluir imports e declaração de pacotes.
  *  Neste exemplo não temos nada a incluir nesta seção.
  */
  

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\3\0\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\12\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\0\1\30\1\31\1\32\2\30"+
    "\1\33\2\30\1\34\21\30\1\35\1\36\1\37\1\0"+
    "\1\40\1\0\1\41\2\42\1\43\1\44\1\45\1\42"+
    "\1\46\1\47\2\42\1\50\1\42\1\51\1\52\1\53"+
    "\1\42\1\54\1\55\1\56\1\57\1\42\1\60\3\42"+
    "\1\61\1\40\1\62\7\0\1\3\44\0\1\42\12\0"+
    "\1\42\4\0\1\42\5\0\27\30\1\0\7\30\30\42"+
    "\1\0\10\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\2\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\2\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\2\30\1\42\1\30\1\42\1\30\3\42\2\30\1\42"+
    "\1\30\1\42\2\30\1\42\3\30\2\42\4\30\1\42"+
    "\2\30\1\42\3\30\3\42\2\30\1\42\2\30\1\42"+
    "\1\30\1\42\1\30\1\42\2\30\1\42\1\30\2\42"+
    "\1\30\1\42\2\30\1\42\3\30\1\42\1\30\1\42"+
    "\2\30\2\42\1\40\1\30\3\42\4\40\1\30\1\40"+
    "\1\42\1\30\1\40\1\42\1\30\1\40\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\2\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\2\42\1\30\1\40\1\42\1\30\1\42\3\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\7\42\2\30\1\42\2\30\2\42\1\30\1\42"+
    "\4\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\105\42\1\40\44\42\7\40\2\42\4\0\14\40"+
    "\16\0\5\42\7\0\1\40\1\0\1\40\126\0\1\63"+
    "\52\0\1\30\1\42\1\30\1\42\1\40\1\0\1\30"+
    "\1\42\2\0\4\42\1\0\1\30\6\0\1\30\1\0"+
    "\3\30\1\0\1\30\1\0\2\30\1\42\21\30\1\0"+
    "\11\30\43\42\1\30\2\42\3\30\3\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\5\42\1\30\1\42"+
    "\1\0\1\30\1\42\2\30\2\42\63\30\60\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\10\0\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\2\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\2\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\0\46\30"+
    "\2\0\1\40\6\0\51\42\107\0\33\40\4\0\4\40"+
    "\55\0\53\40\25\0\12\22\4\0\2\40\1\0\143\40"+
    "\1\0\1\40\17\0\2\40\7\0\2\40\12\22\3\40"+
    "\2\0\1\40\20\0\1\40\1\0\36\40\35\0\131\40"+
    "\13\0\1\40\16\0\12\22\41\40\11\0\2\40\4\0"+
    "\1\40\5\0\26\40\4\0\1\40\11\0\1\40\3\0"+
    "\1\40\27\0\31\40\7\0\13\40\65\0\25\40\1\0"+
    "\10\40\106\0\66\40\3\0\1\40\22\0\1\40\7\0"+
    "\12\40\4\0\12\22\1\0\20\40\4\0\10\40\2\0"+
    "\2\40\2\0\26\40\1\0\7\40\1\0\1\40\3\0"+
    "\4\40\3\0\1\40\20\0\1\40\15\0\2\40\1\0"+
    "\3\40\4\0\12\22\2\40\12\0\1\40\10\0\6\40"+
    "\4\0\2\40\2\0\26\40\1\0\7\40\1\0\2\40"+
    "\1\0\2\40\1\0\2\40\37\0\4\40\1\0\1\40"+
    "\7\0\12\22\2\0\3\40\20\0\11\40\1\0\3\40"+
    "\1\0\26\40\1\0\7\40\1\0\2\40\1\0\5\40"+
    "\3\0\1\40\22\0\1\40\17\0\2\40\4\0\12\22"+
    "\11\0\1\40\13\0\10\40\2\0\2\40\2\0\26\40"+
    "\1\0\7\40\1\0\2\40\1\0\5\40\3\0\1\40"+
    "\36\0\2\40\1\0\3\40\4\0\12\22\1\0\1\40"+
    "\21\0\1\40\1\0\6\40\3\0\3\40\1\0\4\40"+
    "\3\0\2\40\1\0\1\40\1\0\2\40\3\0\2\40"+
    "\3\0\3\40\3\0\14\40\26\0\1\40\25\0\12\22"+
    "\25\0\10\40\1\0\3\40\1\0\27\40\1\0\20\40"+
    "\3\0\1\40\32\0\3\40\5\0\2\40\4\0\12\22"+
    "\20\0\1\40\4\0\10\40\1\0\3\40\1\0\27\40"+
    "\1\0\12\40\1\0\5\40\3\0\1\40\40\0\1\40"+
    "\1\0\2\40\4\0\12\22\1\0\2\40\22\0\10\40"+
    "\1\0\3\40\1\0\51\40\2\0\1\40\20\0\1\40"+
    "\5\0\3\40\10\0\3\40\4\0\12\22\12\0\6\40"+
    "\5\0\22\40\3\0\30\40\1\0\11\40\1\0\1\40"+
    "\2\0\7\40\37\0\12\22\21\0\60\40\1\0\2\40"+
    "\14\0\7\40\11\0\12\22\47\0\2\40\1\0\1\40"+
    "\1\0\5\40\1\0\30\40\1\0\1\40\1\0\12\40"+
    "\1\0\2\40\11\0\1\40\2\0\5\40\1\0\1\40"+
    "\11\0\12\22\2\0\4\40\40\0\1\40\37\0\12\22"+
    "\26\0\10\40\1\0\44\40\33\0\5\40\163\0\53\40"+
    "\24\0\1\40\12\22\6\0\6\40\4\0\4\40\3\0"+
    "\1\40\3\0\2\40\7\0\3\40\4\0\15\40\14\0"+
    "\1\40\1\0\12\22\6\0\46\30\1\0\1\30\5\0"+
    "\1\30\2\0\53\42\1\0\1\40\3\42\u0149\40\1\0"+
    "\4\40\2\0\7\40\1\0\1\40\1\0\4\40\2\0"+
    "\51\40\1\0\4\40\2\0\41\40\1\0\4\40\2\0"+
    "\7\40\1\0\1\40\1\0\4\40\2\0\17\40\1\0"+
    "\71\40\1\0\4\40\2\0\103\40\45\0\20\40\20\0"+
    "\126\30\2\0\6\42\3\0\u016c\40\2\0\21\40\1\0"+
    "\32\40\5\0\113\40\6\0\10\40\7\0\15\40\1\0"+
    "\4\40\16\0\22\40\16\0\22\40\16\0\15\40\1\0"+
    "\3\40\17\0\64\40\43\0\1\40\4\0\1\40\3\0"+
    "\12\22\46\0\12\22\6\0\131\40\7\0\5\40\2\0"+
    "\42\40\1\0\1\40\5\0\106\40\12\0\37\40\47\0"+
    "\12\22\36\40\2\0\5\40\13\0\54\40\4\0\32\40"+
    "\6\0\12\22\46\0\27\40\11\0\65\40\53\0\12\22"+
    "\6\0\12\22\15\0\1\40\135\0\57\40\21\0\7\40"+
    "\4\0\12\22\51\0\36\40\15\0\2\40\12\22\54\40"+
    "\32\0\44\40\34\0\12\22\3\0\3\40\12\22\44\40"+
    "\2\0\11\42\7\0\53\30\2\0\3\30\51\0\4\40"+
    "\1\0\6\40\1\0\2\40\3\0\1\40\5\0\300\42"+
    "\100\0\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\11\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\11\42\10\30\6\42\2\0\6\30\2\0\10\42\10\30"+
    "\10\42\10\30\6\42\2\0\6\30\2\0\10\42\1\0"+
    "\1\30\1\0\1\30\1\0\1\30\1\0\1\30\10\42"+
    "\10\30\16\42\2\0\10\42\10\40\10\42\10\40\10\42"+
    "\10\40\5\42\1\0\2\42\4\30\1\40\1\0\1\42"+
    "\3\0\3\42\1\0\2\42\4\30\1\40\3\0\4\42"+
    "\2\0\2\42\4\30\4\0\10\42\5\30\5\0\3\42"+
    "\1\0\2\42\4\30\1\40\53\0\2\3\107\0\1\42"+
    "\15\0\1\42\20\0\15\42\145\0\1\30\4\0\1\30"+
    "\2\0\1\42\3\30\2\42\3\30\1\42\1\0\1\30"+
    "\3\0\5\30\6\0\1\30\1\0\1\30\1\0\1\30"+
    "\1\0\4\30\1\0\1\42\4\30\1\42\4\40\1\42"+
    "\2\0\2\42\2\30\5\0\1\30\4\42\4\0\1\42"+
    "\21\0\20\64\20\63\3\0\1\30\1\42\u0231\0\32\64"+
    "\32\63\26\0\57\30\1\0\57\42\1\0\1\30\1\42"+
    "\3\30\2\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\4\30\1\42\1\30\2\42\1\30\10\42\3\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\2\42\6\0\1\30\1\42\1\30\1\42\3\0"+
    "\1\30\1\42\14\0\46\42\1\0\1\42\5\0\1\42"+
    "\2\0\70\40\7\0\1\40\20\0\27\40\11\0\7\40"+
    "\1\0\7\40\1\0\7\40\1\0\7\40\1\0\7\40"+
    "\1\0\7\40\1\0\7\40\1\0\7\40\120\0\1\40"+
    "\325\0\2\40\52\0\5\40\5\0\2\40\4\0\126\40"+
    "\6\0\3\40\1\0\132\40\1\0\4\40\5\0\53\40"+
    "\1\0\136\40\21\0\33\40\65\0\306\40\112\0\360\40"+
    "\20\0\215\40\103\0\56\40\2\0\15\40\3\0\20\40"+
    "\12\22\2\40\24\0\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\40\20\0\1\40\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\3\42"+
    "\2\0\106\40\61\0\11\40\2\0\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\3\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\30"+
    "\12\42\1\30\1\42\1\30\1\42\2\30\1\42\1\30"+
    "\1\42\1\30\1\42\1\30\1\42\1\30\1\42\1\40"+
    "\2\0\1\30\1\42\1\30\1\42\1\40\1\30\1\42"+
    "\1\30\3\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\1\30\1\42\5\30\1\42"+
    "\5\30\1\42\1\30\1\42\1\30\1\42\1\30\1\42"+
    "\1\30\1\42\1\30\1\42\2\0\1\30\1\42\3\30"+
    "\60\0\1\40\3\42\7\40\1\0\3\40\1\0\4\40"+
    "\1\0\27\40\35\0\64\40\16\0\62\40\34\0\12\22"+
    "\30\0\6\40\3\0\1\40\1\0\2\40\1\0\12\22"+
    "\34\40\12\0\27\40\31\0\35\40\7\0\57\40\34\0"+
    "\1\40\12\22\6\0\5\40\1\0\12\40\12\22\5\40"+
    "\1\0\51\40\27\0\3\40\1\0\10\40\4\0\12\22"+
    "\6\0\27\40\3\0\1\40\3\0\62\40\1\0\1\40"+
    "\3\0\2\40\2\0\5\40\2\0\1\40\1\0\1\40"+
    "\30\0\3\40\2\0\13\40\7\0\3\40\14\0\6\40"+
    "\2\0\6\40\2\0\6\40\11\0\7\40\1\0\7\40"+
    "\1\0\53\42\1\0\14\42\10\0\120\42\43\40\15\0"+
    "\12\22\6\0\244\40\14\0\27\40\4\0\61\40\4\0"+
    "\u0100\3\156\40\2\0\152\40\46\0\7\42\14\0\5\42"+
    "\5\0\1\40\1\0\12\40\1\0\15\40\1\0\5\40"+
    "\1\0\1\40\1\0\2\40\1\0\2\40\1\0\154\40"+
    "\41\0\153\40\22\0\100\40\2\0\66\40\50\0\14\40"+
    "\164\0\5\40\1\0\207\40\23\0\12\22\7\0\32\30"+
    "\6\0\32\42\13\0\131\40\3\0\6\40\2\0\6\40"+
    "\2\0\6\40\2\0\3\40\43\0\14\40\1\0\32\40"+
    "\1\0\23\40\1\0\2\40\1\0\17\40\2\0\16\40"+
    "\42\0\173\40\205\0\35\40\3\0\61\40\57\0\40\40"+
    "\15\0\24\40\1\0\10\40\6\0\46\40\12\0\36\40"+
    "\2\0\44\40\4\0\10\40\60\0\50\30\50\42\116\40"+
    "\2\0\12\22\6\0\44\30\4\0\44\42\4\0\50\40"+
    "\10\0\64\40\234\0\67\40\11\0\26\40\12\0\10\40"+
    "\230\0\6\40\2\0\1\40\1\0\54\40\1\0\2\40"+
    "\3\0\1\40\2\0\27\40\12\0\27\40\11\0\37\40"+
    "\101\0\23\40\1\0\2\40\12\0\26\40\12\0\32\40"+
    "\106\0\70\40\6\0\2\40\100\0\1\40\17\0\4\40"+
    "\1\0\3\40\1\0\35\40\52\0\35\40\3\0\35\40"+
    "\43\0\10\40\1\0\34\40\33\0\66\40\12\0\26\40"+
    "\12\0\23\40\15\0\22\40\156\0\111\40\67\0\63\30"+
    "\15\0\63\42\15\0\44\40\14\0\12\22\306\0\35\40"+
    "\12\0\1\40\10\0\26\40\232\0\27\40\14\0\65\40"+
    "\56\0\12\22\23\0\55\40\40\0\31\40\7\0\12\22"+
    "\11\0\44\40\17\0\12\22\4\0\1\40\13\0\43\40"+
    "\3\0\1\40\14\0\60\40\16\0\4\40\13\0\12\22"+
    "\1\40\1\0\1\40\43\0\22\40\1\0\31\40\124\0"+
    "\7\40\1\0\1\40\1\0\4\40\1\0\17\40\1\0"+
    "\12\40\7\0\57\40\21\0\12\22\13\0\10\40\2\0"+
    "\2\40\2\0\26\40\1\0\7\40\1\0\2\40\1\0"+
    "\5\40\3\0\1\40\22\0\1\40\14\0\5\40\236\0"+
    "\65\40\22\0\4\40\5\0\12\22\5\0\1\40\40\0"+
    "\60\40\24\0\2\40\1\0\1\40\10\0\12\22\246\0"+
    "\57\40\51\0\4\40\44\0\60\40\24\0\1\40\13\0"+
    "\12\22\46\0\53\40\15\0\1\40\7\0\12\22\66\0"+
    "\33\40\25\0\12\22\306\0\54\40\164\0\40\30\40\42"+
    "\12\22\25\0\1\40\240\0\10\40\2\0\47\40\20\0"+
    "\1\40\1\0\1\40\34\0\1\40\12\0\50\40\7\0"+
    "\1\40\25\0\1\40\13\0\56\40\23\0\1\40\42\0"+
    "\71\40\7\0\11\40\1\0\45\40\21\0\1\40\17\0"+
    "\12\22\30\0\36\40\160\0\7\40\1\0\2\40\1\0"+
    "\46\40\25\0\1\40\11\0\12\22\6\0\6\40\1\0"+
    "\2\40\1\0\40\40\16\0\1\40\7\0\12\22\u0136\0"+
    "\23\40\15\0\232\40\346\0\304\40\274\0\57\40\321\0"+
    "\107\40\271\0\71\40\7\0\37\40\1\0\12\22\146\0"+
    "\36\40\22\0\60\40\20\0\4\40\14\0\12\22\11\0"+
    "\25\40\5\0\23\40\260\0\40\30\40\42\200\0\113\40"+
    "\5\0\1\40\102\0\15\40\100\0\2\40\1\0\1\40"+
    "\34\0\370\40\10\0\363\40\15\0\37\40\61\0\3\40"+
    "\21\0\4\40\10\0\u018c\40\4\0\153\40\5\0\15\40"+
    "\3\0\11\40\7\0\12\40\146\0\32\30\32\42\32\30"+
    "\7\42\1\0\22\42\32\30\32\42\1\30\1\0\2\30"+
    "\2\0\1\30\2\0\2\30\2\0\4\30\1\0\10\30"+
    "\4\42\1\0\1\42\1\0\7\42\1\0\13\42\32\30"+
    "\32\42\2\30\1\0\4\30\2\0\10\30\1\0\7\30"+
    "\1\0\32\42\2\30\1\0\4\30\1\0\5\30\1\0"+
    "\1\30\3\0\7\30\1\0\32\42\32\30\32\42\32\30"+
    "\32\42\32\30\32\42\32\30\32\42\32\30\32\42\32\30"+
    "\34\42\2\0\31\30\1\0\31\42\1\0\6\42\31\30"+
    "\1\0\31\42\1\0\6\42\31\30\1\0\31\42\1\0"+
    "\6\42\31\30\1\0\31\42\1\0\6\42\31\30\1\0"+
    "\31\42\1\0\6\42\1\30\1\42\2\0\62\22\55\40"+
    "\12\0\7\40\2\0\12\22\4\0\1\40\u0171\0\54\40"+
    "\4\0\12\22\6\0\305\40\73\0\42\30\42\42\7\0"+
    "\1\40\4\0\12\22\246\0\4\40\1\0\33\40\1\0"+
    "\2\40\1\0\1\40\2\0\1\40\1\0\12\40\1\0"+
    "\4\40\1\0\1\40\1\0\1\40\6\0\1\40\4\0"+
    "\1\40\1\0\1\40\1\0\1\40\1\0\3\40\1\0"+
    "\2\40\1\0\1\40\2\0\1\40\1\0\1\40\1\0"+
    "\1\40\1\0\1\40\1\0\1\40\1\0\2\40\1\0"+
    "\1\40\2\0\4\40\1\0\7\40\1\0\4\40\1\0"+
    "\4\40\1\0\1\40\1\0\12\40\1\0\21\40\5\0"+
    "\3\40\1\0\5\40\1\0\21\40\164\0\32\64\6\0"+
    "\32\64\6\0\32\64\166\0\327\40\51\0\65\40\13\0"+
    "\336\40\2\0\u0182\40\16\0\u0131\40\37\0\36\40\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\5\23\1\24\1\25\11\26"+
    "\1\27\1\30\1\31\1\32\3\0\1\33\1\0\1\34"+
    "\1\35\4\23\3\26\1\36\6\26\1\0\2\37\3\23"+
    "\1\40\4\26\1\41\4\26\1\0\1\42\1\43\1\23"+
    "\1\44\1\45\2\26\1\46\1\26\1\47\1\50\1\2"+
    "\1\51\1\52\1\26\1\53\1\26\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\152\0\237\0\324\0\152\0\u0109"+
    "\0\u013e\0\152\0\152\0\152\0\152\0\152\0\u0173\0\u01a8"+
    "\0\152\0\u01dd\0\u0212\0\152\0\152\0\u0247\0\152\0\u027c"+
    "\0\u02b1\0\u02e6\0\u031b\0\u0350\0\152\0\152\0\u0385\0\u03ba"+
    "\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562"+
    "\0\152\0\152\0\152\0\u0597\0\u05cc\0\u0601\0\u01a8\0\u01a8"+
    "\0\152\0\152\0\u0636\0\u066b\0\u06a0\0\u06d5\0\u070a\0\u073f"+
    "\0\u0774\0\u0385\0\u07a9\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2"+
    "\0\u08e7\0\152\0\u0597\0\u091c\0\u0951\0\u0986\0\u027c\0\u09bb"+
    "\0\u09f0\0\u0a25\0\u0a5a\0\u0385\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e"+
    "\0\u0b63\0\u027c\0\u027c\0\u0b98\0\u0385\0\u0385\0\u0bcd\0\u0c02"+
    "\0\u0385\0\u0c37\0\u0385\0\u0385\0\u08e7\0\u027c\0\u0385\0\u0c6c"+
    "\0\u0385\0\u0ca1\0\u0385";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\3\1\36\1\3"+
    "\2\37\1\40\1\41\1\42\1\37\1\43\1\37\1\44"+
    "\1\37\1\45\1\46\1\37\1\47\2\37\1\50\1\51"+
    "\1\37\1\30\65\3\67\0\1\4\110\0\1\52\46\0"+
    "\1\53\54\0\2\54\4\0\30\54\1\55\26\54\17\0"+
    "\1\56\67\0\1\57\62\0\1\60\1\0\1\22\65\0"+
    "\1\61\67\0\1\62\60\0\1\30\5\0\5\30\3\0"+
    "\21\30\26\0\1\30\5\0\5\30\3\0\12\30\1\63"+
    "\6\30\26\0\1\30\5\0\5\30\3\0\6\30\1\64"+
    "\12\30\26\0\1\30\5\0\5\30\3\0\10\30\1\65"+
    "\10\30\26\0\1\30\5\0\5\30\3\0\11\30\1\66"+
    "\7\30\26\0\1\37\5\0\5\37\3\0\21\37\26\0"+
    "\1\37\5\0\5\37\3\0\1\37\1\67\17\37\26\0"+
    "\1\37\5\0\5\37\3\0\10\37\1\70\10\37\26\0"+
    "\1\37\5\0\5\37\3\0\1\37\1\71\17\37\26\0"+
    "\1\37\5\0\5\37\3\0\5\37\1\72\10\37\1\73"+
    "\2\37\26\0\1\37\5\0\5\37\3\0\4\37\1\74"+
    "\12\37\1\75\1\37\26\0\1\37\5\0\5\37\3\0"+
    "\14\37\1\76\4\37\26\0\1\37\5\0\5\37\3\0"+
    "\4\37\1\77\14\37\26\0\1\37\5\0\5\37\3\0"+
    "\14\37\1\100\4\37\23\0\1\101\56\0\1\102\64\0"+
    "\1\103\24\0\1\54\12\0\1\54\2\0\1\54\1\0"+
    "\1\54\6\0\2\56\1\4\2\0\1\5\57\56\22\0"+
    "\1\30\5\0\5\30\3\0\12\30\1\104\6\30\26\0"+
    "\1\30\5\0\5\30\3\0\1\30\1\105\17\30\26\0"+
    "\1\30\5\0\5\30\3\0\12\30\1\106\6\30\26\0"+
    "\1\30\5\0\5\30\3\0\16\30\1\107\2\30\26\0"+
    "\1\37\5\0\5\37\3\0\16\37\1\110\2\37\26\0"+
    "\1\37\5\0\5\37\3\0\15\37\1\111\3\37\26\0"+
    "\1\37\5\0\5\37\3\0\10\37\1\112\10\37\26\0"+
    "\1\37\5\0\5\37\3\0\4\37\1\113\14\37\26\0"+
    "\1\37\5\0\5\37\3\0\20\37\1\114\26\0\1\37"+
    "\5\0\5\37\3\0\10\37\1\115\10\37\26\0\1\37"+
    "\5\0\5\37\3\0\7\37\1\116\11\37\26\0\1\37"+
    "\5\0\5\37\3\0\1\37\1\117\17\37\26\0\1\37"+
    "\5\0\5\37\3\0\17\37\1\120\1\37\4\0\2\101"+
    "\4\0\11\101\1\121\45\101\22\0\1\30\5\0\5\30"+
    "\3\0\10\30\1\122\10\30\26\0\1\30\5\0\5\30"+
    "\3\0\14\30\1\123\4\30\26\0\1\30\5\0\5\30"+
    "\3\0\1\30\1\124\17\30\26\0\1\37\5\0\5\37"+
    "\3\0\1\37\1\125\17\37\26\0\1\37\5\0\5\37"+
    "\3\0\4\37\1\126\14\37\26\0\1\37\5\0\5\37"+
    "\3\0\15\37\1\127\3\37\26\0\1\37\5\0\5\37"+
    "\3\0\14\37\1\130\4\37\26\0\1\37\5\0\5\37"+
    "\3\0\10\37\1\131\10\37\26\0\1\37\5\0\5\37"+
    "\3\0\11\37\1\132\7\37\26\0\1\37\5\0\5\37"+
    "\3\0\3\37\1\133\15\37\26\0\1\37\5\0\5\37"+
    "\3\0\4\37\1\134\14\37\4\0\2\101\4\0\11\101"+
    "\1\121\42\101\1\135\2\101\22\0\1\30\5\0\5\30"+
    "\3\0\16\30\1\136\2\30\26\0\1\37\5\0\5\37"+
    "\3\0\4\37\1\137\14\37\26\0\1\37\5\0\5\37"+
    "\3\0\1\37\1\140\17\37\26\0\1\37\5\0\5\37"+
    "\3\0\16\37\1\141\2\37\26\0\1\37\5\0\5\37"+
    "\3\0\16\37\1\142\2\37\26\0\1\37\5\0\5\37"+
    "\3\0\4\37\1\143\14\37\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3286];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\5\11\2\1\1\11"+
    "\2\1\2\11\1\1\1\11\5\1\2\11\12\1\3\11"+
    "\3\0\1\1\1\0\2\11\16\1\1\0\1\11\16\1"+
    "\1\0\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    
    /* Código arbitrário pode ser inserido diretamente no analisador dessa forma. 
     * Aqui podemos declarar variáveis e métodos adicionais que julgarmos necessários. 
     */
    private int ntk;
    
    public int readedTokens(){
       return ntk;
    }

    private Token symbol(TOKEN_TYPE t) {
        ntk++;
        return new Token(t, yyline+1, yycolumn+1);
        
    }

    private Token symbol(TOKEN_TYPE t, String s) {
        ntk++;
        return new Token(t, s, yyline+1, yycolumn+1);
        
    }
    private Token symbol(TOKEN_TYPE t, Object value) {
        ntk++;
        return new Token(t, value, yyline+1, yycolumn+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
      ntk = 0; // Isto é copiado direto no construtor do lexer. 
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
            // fall through
          case 45: break;
          case 2:
            { 
            }
            // fall through
          case 46: break;
          case 3:
            { return symbol(TOKEN_TYPE.NEGATION, yytext());
            }
            // fall through
          case 47: break;
          case 4:
            { return symbol(TOKEN_TYPE.MOD, yytext());
            }
            // fall through
          case 48: break;
          case 5:
            { return symbol(TOKEN_TYPE.PARENTHESES_OPEN, yytext());
            }
            // fall through
          case 49: break;
          case 6:
            { return symbol(TOKEN_TYPE.PARENTHESES_CLOSE, yytext());
            }
            // fall through
          case 50: break;
          case 7:
            { return symbol(TOKEN_TYPE.TIMES, yytext());
            }
            // fall through
          case 51: break;
          case 8:
            { return symbol(TOKEN_TYPE.PLUS, yytext());
            }
            // fall through
          case 52: break;
          case 9:
            { return symbol(TOKEN_TYPE.COMMA, yytext());
            }
            // fall through
          case 53: break;
          case 10:
            { return symbol(TOKEN_TYPE.SUBTRACTION, yytext());
            }
            // fall through
          case 54: break;
          case 11:
            { return symbol(TOKEN_TYPE.PERIOD, yytext());
            }
            // fall through
          case 55: break;
          case 12:
            { return symbol(TOKEN_TYPE.DIVISION, yytext());
            }
            // fall through
          case 56: break;
          case 13:
            { return symbol(TOKEN_TYPE.INT_VALUE, Integer.parseInt(yytext()) );
            }
            // fall through
          case 57: break;
          case 14:
            { return symbol(TOKEN_TYPE.COLON, yytext());
            }
            // fall through
          case 58: break;
          case 15:
            { return symbol(TOKEN_TYPE.SEMI, yytext());
            }
            // fall through
          case 59: break;
          case 16:
            { return symbol(TOKEN_TYPE.LESS_THAN, yytext());
            }
            // fall through
          case 60: break;
          case 17:
            { return symbol(TOKEN_TYPE.EQ, yytext());
            }
            // fall through
          case 61: break;
          case 18:
            { return symbol(TOKEN_TYPE.MORE_THAN, yytext());
            }
            // fall through
          case 62: break;
          case 19:
            { return symbol(TOKEN_TYPE.TYPE, yytext());
            }
            // fall through
          case 63: break;
          case 20:
            { return symbol(TOKEN_TYPE.BRACKETS_OPEN, yytext());
            }
            // fall through
          case 64: break;
          case 21:
            { return symbol(TOKEN_TYPE.BRACKETS_CLOSE, yytext());
            }
            // fall through
          case 65: break;
          case 22:
            { return symbol(TOKEN_TYPE.ID_VALUE, yytext());
            }
            // fall through
          case 66: break;
          case 23:
            { return symbol(TOKEN_TYPE.BRACES_OPEN, yytext());
            }
            // fall through
          case 67: break;
          case 24:
            { return symbol(TOKEN_TYPE.BRACES_CLOSE, yytext());
            }
            // fall through
          case 68: break;
          case 25:
            { return symbol(TOKEN_TYPE.DIFFERENT, yytext());
            }
            // fall through
          case 69: break;
          case 26:
            { return symbol(TOKEN_TYPE.AND, yytext());
            }
            // fall through
          case 70: break;
          case 27:
            { return symbol(TOKEN_TYPE.FLOAT_VALUE, Float.parseFloat(yytext()) );
            }
            // fall through
          case 71: break;
          case 28:
            { return symbol(TOKEN_TYPE.TWO_COLON, yytext());
            }
            // fall through
          case 72: break;
          case 29:
            { return symbol(TOKEN_TYPE.EQ_LOGIC, yytext());
            }
            // fall through
          case 73: break;
          case 30:
            { return symbol(TOKEN_TYPE.IF, yytext());
            }
            // fall through
          case 74: break;
          case 31:
            { return symbol(TOKEN_TYPE.CHAR_VALUE, yytext());
            }
            // fall through
          case 75: break;
          case 32:
            { return symbol(TOKEN_TYPE.INT, yytext());
            }
            // fall through
          case 76: break;
          case 33:
            { return symbol(TOKEN_TYPE.NEW, yytext());
            }
            // fall through
          case 77: break;
          case 34:
            { return symbol(TOKEN_TYPE.BOOL, yytext());
            }
            // fall through
          case 78: break;
          case 35:
            { return symbol(TOKEN_TYPE.CHAR, yytext());
            }
            // fall through
          case 79: break;
          case 36:
            { return symbol(TOKEN_TYPE.DATA, yytext());
            }
            // fall through
          case 80: break;
          case 37:
            { return symbol(TOKEN_TYPE.ELSE, yytext());
            }
            // fall through
          case 81: break;
          case 38:
            { return symbol(TOKEN_TYPE.NULL, yytext());
            }
            // fall through
          case 82: break;
          case 39:
            { return symbol(TOKEN_TYPE.READ, yytext());
            }
            // fall through
          case 83: break;
          case 40:
            { return symbol(TOKEN_TYPE.TRUE, yytext());
            }
            // fall through
          case 84: break;
          case 41:
            { return symbol(TOKEN_TYPE.FLOAT, yytext());
            }
            // fall through
          case 85: break;
          case 42:
            { return symbol(TOKEN_TYPE.FALSE, yytext());
            }
            // fall through
          case 86: break;
          case 43:
            { return symbol(TOKEN_TYPE.PRINT, yytext());
            }
            // fall through
          case 87: break;
          case 44:
            { return symbol(TOKEN_TYPE.ITERATE, yytext());
            }
            // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
