java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste0.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste1.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste1eMeio.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste2.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste3.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste4.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste5.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste6.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste7.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste8.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste9.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste10.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste11.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/certo/teste12.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/attrAND.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/attrFALSE.cmd
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/data0.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/data1.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/data2.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/function_call_expr.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/function_call_ret_use.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/function0.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/function1.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/if_oneCMD.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/if_teste.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/ifelse_oneCMD.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/instanciate.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/instanciate1.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/main_args.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/main_missing.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/parameters.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/parameters1.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/parameters2.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/return.lan
java -cp .:antlr-4.8-complete.jar Intepretador testes/semantica/errado/teste8.lan